[package]
name = "common"
version = "0.0.1"
edition = "2021"

[dependencies]
tonic = "0.12"
prost = "0.13"
tokio = { version = "1.42", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
hostname = "0.4"

[build-dependencies]
tonic-build = "0.12"
