[package]
name = "agent"
version = "0.0.3"
edition = "2021"

[dependencies]
common = { path = "../common" }
tonic = "0.12"
tokio = { version = "1.42", features = ["full"] }
sysinfo = "0.38.2"
tracing = "0.1"
anyhow = "1.0"
hostname = "0.4"
tokio-stream = "0.1.18"
once_cell = "1.20"
